kind: pipeline
type: docker
name: default

steps:
- name: lint
  image: python:3.7-alpine
  commands:
  - python -m pip install -r requirements.txt
  - flake8
 
trigger:
  repo:
    include:
    - DroneTest-Seint/Drone-testing
