kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
