kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang 
  failure: ignore
  commands:
  - go build
  - go test

- name: frontend
  image: node
  commands:
  - npm install
  - npm test
