kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: doker_username

---
kind: secret
name: doker_username
data: kZd11sq2wywOtOXXlMLJ9CH56OnMCS2tH2Iml2P7u5Hh8Ag0gFLESFw1
