kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: DroneTest-Seint/Drone-testing
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
