kind: pipeline
name: testing

steps:
- name: first
  image: php
  commands:
  - echo “Output from first step”;

- name: second
  image: php
  commands:
  - echo “Output from second step”;

  depends_on:
  - first
  - second
